name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Forge
        run: cargo install --git https://github.com/gakonst/foundry --bin forge --locked
      - name: Install Dependencies
        run: yarn
      - name: Update Modules
        run: yarn sync
      - name: Run Tests
        run: yarn test